language: java
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "TravisCI"
  - git config --local user.email "cyberflameu@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $token
  file: "KPM.jar"
  cleanup: true
  on:
    branch: master
