# For the block destroyer module of this plugin

# If you want to remove all entries, uncomment the brackets
disabled-worlds: #[]
  - disabled-world

# For the armor module of this plugin

# All blocks with an inventory or any blocks that when right clicked shouldn't equip armor.
blocked:
  - FURNACE
  - CHEST
  - TRAPPED_CHEST
  - BEACON
  - DISPENSER
  - DROPPER
  - HOPPER
  - WORKBENCH
  - ENCHANTMENT_TABLE
  - ENDER_CHEST
  - ANVIL
  - BED_BLOCK
  - FENCE_GATE
  - SPRUCE_FENCE_GATE
  - BIRCH_FENCE_GATE
  - ACACIA_FENCE_GATE
  - JUNGLE_FENCE_GATE
  - DARK_OAK_FENCE_GATE
  - IRON_DOOR_BLOCK
  - WOODEN_DOOR
  - SPRUCE_DOOR
  - BIRCH_DOOR
  - JUNGLE_DOOR
  - ACACIA_DOOR
  - DARK_OAK_DOOR
  - WOOD_BUTTON
  - STONE_BUTTON
  - TRAP_DOOR
  - IRON_TRAPDOOR
  - DIODE_BLOCK_OFF
  - DIODE_BLOCK_ON
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - FENCE
  - SPRUCE_FENCE
  - BIRCH_FENCE
  - JUNGLE_FENCE
  - DARK_OAK_FENCE
  - ACACIA_FENCE
  - NETHER_FENCE
  - BREWING_STAND
  - CAULDRON
  - SIGN
  - LEVER
  - DAYLIGHT_DETECTOR_INVERTED
  - DAYLIGHT_DETECTOR
  - ANVIL

# Bow fix settings
settings:
  reduce-damage: 25.0 # Reduce damage by this percent (e.g. 100.0 - bow boosting doesn't cause damage).
  velocity-multiplier: 2.5 # The higher the velocity multiplier the further the player will travel.
  punch-only: false # Should bow boosting only work for punch bows?