name: ${project.name}
version: ${project.version}
main: net.cyberflame.kpm.KPM
description: KPM is a plugin made by CyberFlame primarily for OuterWorlds. This was updated by StarZorrow (zorurruan) and I thank him very much for his modifications to it as the original was kinda sloppy.
author: Owner_of_Mojang (CyberFlame)
permissions:
  kpm.buildmode:
    description: Allows the user to run /buildmode
    default: op
commands:
  buildmode:
    description: Buildmode toggle root command
    permission: kpm.buildmode
    usage: /buildmode