name: KPM
version: 1.0.0
main: net.cyberflame.kpm.KPM
description: KPM is a plugin made by CyberFlame primarily for OuterWorlds. This was updated by StarZorrow (zorurruan) and I thank him very much for his modifications to it as the original was kinda sloppy.
author: Owner_of_Mojang (CyberFlame)
permissions:
  kpm.*:
    description: KPM root command
    default: op
    children:
      kpm.root: true
      kpm.buildmode: true
      kpm.override: true
      kpm.reload: true
      kpm.ping: true
      kpm.ping.others: true
      kpm.setknockback: true
      kpm.charfix: true
  kpm.root:
    description: KPM root
  kpm.buildmode:
    description: Allows the user to run /buildmode
    default: op
  kpm.override:
    description: Allows player to bypass the anti block glitch
    default: op
  kpm.ping.others:
    description: Allows access to viewing others' pings
    default: op
    children:
      kpm.ping: true
  kpm.ping:
    description: Allows access to /ping
    default: true
  kpm.setknockback:
    description: Allows editing of knockback values
    default: op
  kpm.charfix:
    description: Fix glitching character
    default: true
commands:
  kpm:
    description: KPM command
    permission: kpm.root
    usage: /kpm [reload]
  buildmode:
    description: Buildmode toggle command
    permission: kpm.buildmode
    usage: /buildmode
  splashpotionspeed:
    description: SplashPotionSpeed commands
    usage: /splashpotionspeed <get/set> <arguments>
  ping:
    description: Check ping
    permission: kpm.ping
    usage: /ping [player]
  setknockback:
    description: Set knockback
    permission: kpm.setknockback
    aliases: [ setkb ]
  characterfix:
    description: Fix character
    permission: kpm.charfix